[project]
name = "qa-generator"
version = "0.1.0"
description = "QA Dataset Generator"
requires-python = ">=3.13"
dependencies = [
    "export>=0.2.1",
    "google-genai>=1.23.0",
    "json-repair>=0.47.4",
    "pandas>=2.3.0",
    "python-dotenv>=1.1.1",
    "pydantic-settings>=2.10.1"
]
